# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/jpereiratrindade/labeco10T/dev/cpp/SisterSTRATA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /run/media/jpereiratrindade/labeco10T/dev/cpp/SisterSTRATA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /run/media/jpereiratrindade/labeco10T/dev/cpp/SisterSTRATA/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/jpereiratrindade/labeco10T/dev/cpp/SisterSTRATA/CMakeFiles /run/media/jpereiratrindade/labeco10T/dev/cpp/SisterSTRATA//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/jpereiratrindade/labeco10T/dev/cpp/SisterSTRATA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SisterSTRATA

# Build rule for target.
SisterSTRATA: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SisterSTRATA
.PHONY : SisterSTRATA

# fast build rule for target.
SisterSTRATA/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SisterSTRATA.dir/build.make CMakeFiles/SisterSTRATA.dir/build
.PHONY : SisterSTRATA/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f src/core/CMakeFiles/core.dir/build.make src/core/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named infrastructure

# Build rule for target.
infrastructure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 infrastructure
.PHONY : infrastructure

# fast build rule for target.
infrastructure/fast:
	$(MAKE) $(MAKESILENT) -f src/infrastructure/CMakeFiles/infrastructure.dir/build.make src/infrastructure/CMakeFiles/infrastructure.dir/build
.PHONY : infrastructure/fast

#=============================================================================
# Target rules for targets named application

# Build rule for target.
application: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 application
.PHONY : application

# fast build rule for target.
application/fast:
	$(MAKE) $(MAKESILENT) -f src/application/CMakeFiles/application.dir/build.make src/application/CMakeFiles/application.dir/build
.PHONY : application/fast

#=============================================================================
# Target rules for targets named world3d

# Build rule for target.
world3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 world3d
.PHONY : world3d

# fast build rule for target.
world3d/fast:
	$(MAKE) $(MAKESILENT) -f src/world3d/CMakeFiles/world3d.dir/build.make src/world3d/CMakeFiles/world3d.dir/build
.PHONY : world3d/fast

#=============================================================================
# Target rules for targets named Shaders

# Build rule for target.
Shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Shaders
.PHONY : Shaders

# fast build rule for target.
Shaders/fast:
	$(MAKE) $(MAKESILENT) -f src/world3d/CMakeFiles/Shaders.dir/build.make src/world3d/CMakeFiles/Shaders.dir/build
.PHONY : Shaders/fast

#=============================================================================
# Target rules for targets named ui

# Build rule for target.
ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui
.PHONY : ui

# fast build rule for target.
ui/fast:
	$(MAKE) $(MAKESILENT) -f src/ui/CMakeFiles/ui.dir/build.make src/ui/CMakeFiles/ui.dir/build
.PHONY : ui/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named core_tests

# Build rule for target.
core_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core_tests
.PHONY : core_tests

# fast build rule for target.
core_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/core/CMakeFiles/core_tests.dir/build.make tests/core/CMakeFiles/core_tests.dir/build
.PHONY : core_tests/fast

#=============================================================================
# Target rules for targets named patch_analysis_tests

# Build rule for target.
patch_analysis_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 patch_analysis_tests
.PHONY : patch_analysis_tests

# fast build rule for target.
patch_analysis_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/core/CMakeFiles/patch_analysis_tests.dir/build.make tests/core/CMakeFiles/patch_analysis_tests.dir/build
.PHONY : patch_analysis_tests/fast

#=============================================================================
# Target rules for targets named soil_rasterizer_tests

# Build rule for target.
soil_rasterizer_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soil_rasterizer_tests
.PHONY : soil_rasterizer_tests

# fast build rule for target.
soil_rasterizer_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/core/CMakeFiles/soil_rasterizer_tests.dir/build.make tests/core/CMakeFiles/soil_rasterizer_tests.dir/build
.PHONY : soil_rasterizer_tests/fast

#=============================================================================
# Target rules for targets named patch_trajectory_test

# Build rule for target.
patch_trajectory_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 patch_trajectory_test
.PHONY : patch_trajectory_test

# fast build rule for target.
patch_trajectory_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/core/CMakeFiles/patch_trajectory_test.dir/build.make tests/core/CMakeFiles/patch_trajectory_test.dir/build
.PHONY : patch_trajectory_test/fast

#=============================================================================
# Target rules for targets named trajectory_lod_tests

# Build rule for target.
trajectory_lod_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trajectory_lod_tests
.PHONY : trajectory_lod_tests

# fast build rule for target.
trajectory_lod_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/core/CMakeFiles/trajectory_lod_tests.dir/build.make tests/core/CMakeFiles/trajectory_lod_tests.dir/build
.PHONY : trajectory_lod_tests/fast

#=============================================================================
# Target rules for targets named veg_vector_tests

# Build rule for target.
veg_vector_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 veg_vector_tests
.PHONY : veg_vector_tests

# fast build rule for target.
veg_vector_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/core/CMakeFiles/veg_vector_tests.dir/build.make tests/core/CMakeFiles/veg_vector_tests.dir/build
.PHONY : veg_vector_tests/fast

#=============================================================================
# Target rules for targets named observational_tests_legacy

# Build rule for target.
observational_tests_legacy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 observational_tests_legacy
.PHONY : observational_tests_legacy

# fast build rule for target.
observational_tests_legacy/fast:
	$(MAKE) $(MAKESILENT) -f tests/observational/CMakeFiles/observational_tests_legacy.dir/build.make tests/observational/CMakeFiles/observational_tests_legacy.dir/build
.PHONY : observational_tests_legacy/fast

#=============================================================================
# Target rules for targets named observational_impact_tests

# Build rule for target.
observational_impact_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 observational_impact_tests
.PHONY : observational_impact_tests

# fast build rule for target.
observational_impact_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/observational/CMakeFiles/observational_impact_tests.dir/build.make tests/observational/CMakeFiles/observational_impact_tests.dir/build
.PHONY : observational_impact_tests/fast

#=============================================================================
# Target rules for targets named application_tests

# Build rule for target.
application_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 application_tests
.PHONY : application_tests

# fast build rule for target.
application_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/application/CMakeFiles/application_tests.dir/build.make tests/application/CMakeFiles/application_tests.dir/build
.PHONY : application_tests/fast

#=============================================================================
# Target rules for targets named application_mapper_tests

# Build rule for target.
application_mapper_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 application_mapper_tests
.PHONY : application_mapper_tests

# fast build rule for target.
application_mapper_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/application/CMakeFiles/application_mapper_tests.dir/build.make tests/application/CMakeFiles/application_mapper_tests.dir/build
.PHONY : application_mapper_tests/fast

#=============================================================================
# Target rules for targets named infrastructure_tests

# Build rule for target.
infrastructure_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 infrastructure_tests
.PHONY : infrastructure_tests

# fast build rule for target.
infrastructure_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/infrastructure/CMakeFiles/infrastructure_tests.dir/build.make tests/infrastructure/CMakeFiles/infrastructure_tests.dir/build
.PHONY : infrastructure_tests/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SisterSTRATA.dir/build.make CMakeFiles/SisterSTRATA.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SisterSTRATA.dir/build.make CMakeFiles/SisterSTRATA.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SisterSTRATA.dir/build.make CMakeFiles/SisterSTRATA.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Shaders"
	@echo "... SisterSTRATA"
	@echo "... application"
	@echo "... application_mapper_tests"
	@echo "... application_tests"
	@echo "... core"
	@echo "... core_tests"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... infrastructure"
	@echo "... infrastructure_tests"
	@echo "... observational_impact_tests"
	@echo "... observational_tests_legacy"
	@echo "... patch_analysis_tests"
	@echo "... patch_trajectory_test"
	@echo "... soil_rasterizer_tests"
	@echo "... trajectory_lod_tests"
	@echo "... ui"
	@echo "... veg_vector_tests"
	@echo "... world3d"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

