import math
import os
import sys

def get_height(x, y):
    # Procedural Height Function (Shared Logic)
    # Scale x, y for noise freq
    i = x
    j = y
    
    val = math.sin(i * 0.1) * math.cos(j * 0.1) * 5.0
    
    # Central Peak
    # Assuming center is roughly around coordinate 50,50 
    # But wait, x/y are world coords here.
    # In loop, x=spacing*i.
    # Let's assume input x,y are consistent with loop
    
    # Needs center ref. Let's just hardcode center at 50,50 for now as in prev logic
    cx, cy = 50.0, 50.0 
    dist_sq = (x - cx)**2 + (y - cy)**2
    val += math.exp(-dist_sq / 200.0) * 30.0
    
    val += math.sin(i * 0.5) * math.cos(j * 0.5) * 1.0
    return val

def normalize(v):
    l = math.sqrt(v[0]*v[0] + v[1]*v[1] + v[2]*v[2])
    if l == 0: return (0, 0, 1)
    return (v[0]/l, v[1]/l, v[2]/l)

def generate_terrain(filename, width, height, spacing):
    # Ensure directory exists
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    
    print(f"Generating terrain {width}x{height} to {filename}...")
    vertices = []
    normals = []
    
    # Center Offset for Peak Logic
    cx = (width * spacing) / 2.0
    cy = (height * spacing) / 2.0
    
    # Redefine height func with closure for center
    def h_func(x, y):
        # Base
        val = math.sin(x * 0.1) * math.cos(y * 0.1) * 5.0
        # Peak
        d2 = (x - cx)**2 + (y - cy)**2
        val += math.exp(-d2 / 5000.0) * 40.0 # Tweak: Wider peak
        # Noise
        val += math.sin(x * 0.3) * math.cos(y * 0.3) * 1.5
        return val

    # Generate Vertices & Normals
    for i in range(width):
        for j in range(height):
            x = i * spacing
            y = j * spacing
            z = h_func(x, y)
            
            vertices.append((x, y, z))
            
            # Analytic Normal
            # dZ/dX approx = (h(x+e) - h(x-e)) / 2e
            eps = 0.1
            hl = h_func(x - eps, y)
            hr = h_func(x + eps, y)
            hd = h_func(x, y - eps)
            hu = h_func(x, y + eps)
            
            # Tangent vectors
            # Tx = (2*eps, 0, hr - hl)
            # Ty = (0, 2*eps, hu - hd)
            tx = (2*eps, 0.0, hr - hl)
            ty = (0.0, 2*eps, hu - hd)
            
            # Normal = Cross(Tx, Ty)
            # Nx = Ty.z * Tx.y - Ty.y * Tx.z = 0 - 2eps*(hr-hl) ??
            # Cross Product Rule:
            #  i   j   k
            # tx0 tx1 tx2
            # ty0 ty1 ty2
            
            # nx = tx1*ty2 - tx2*ty1 = 0 - (hr-hl)*2eps
            # ny = tx2*ty0 - tx0*ty2 = (hr-hl)*0 - 2eps*(hu-hd)
            # nz = tx0*ty1 - tx1*ty0 = 2eps*2eps - 0
            
            nx = -2.0 * eps * (hr - hl) # Actually simpler: -dz/dx
            ny = -2.0 * eps * (hu - hd) # -dz/dy
            nz = 4.0 * eps * eps        # 1 (scaled)
            
            normals.append(normalize((nx, ny, nz)))
            
    # Generate Faces (Triangles)
    faces = []
    for i in range(width - 1):
        for j in range(height - 1):
            # Indices match exactly because we generate V and N in same order
            # 1-based index
            base = i * height + j + 1
            
            # Quad corners
            # v1 -- v3 (col j, j+1 is inner loop?) -> WAIT.
            # Inner loop is j (height).
            # v(i, j)   = i*height + j
            # v(i, j+1) = i*height + j + 1
            # v(i+1, j) = (i+1)*height + j
            
            v1 = i * height + j + 1
            v2 = i * height + (j+1) + 1
            v3 = (i+1) * height + j + 1
            v4 = (i+1) * height + (j+1) + 1
            
            # Face 1: v1-v2-v3
            # Face 2: v2-v4-v3
            
            faces.append((v1, v2, v3))
            faces.append((v2, v4, v3))

    with open(filename, 'w') as f:
        f.write("# Procedural Terrain generated by SisterPEC\n")
        f.write(f"o Terrain\n")
        for v in vertices:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")
        
        for n in normals:
            f.write(f"vn {n[0]:.4f} {n[1]:.4f} {n[2]:.4f}\n")
            
        for face in faces:
            # f v//vn v//vn v//vn (since no vt)
            f.write(f"f {face[0]}//{face[0]} {face[1]}//{face[1]} {face[2]}//{face[2]}\n")
            
    print(f"Terrain generation complete: {len(vertices)} vertices, {len(faces)} faces.")

if __name__ == "__main__":
    # Generate in assets/data
    output_path = "assets/data/terrain_sample.obj"
    if len(sys.argv) > 1:
        output_path = sys.argv[1]
        
    generate_terrain(output_path, 100, 100, 2.0) # 2.0 spacing for larger terrain
